export const drugs = [
  {
    id: 'drug1',
    tradeName: 'Panadol',
    genericName: 'Paracetamol',
    pharmacyId: 'pharmacy1',
    price: 500,
    dosageForm: 'Tablet',
    dosageStrength: '500mg',
  },
  {
    id: 'drug2',
    tradeName: 'Augmentin',
    genericName: 'Amoxicillin + Clavulanic Acid',
    pharmacyId: 'pharmacy2',
    price: 3200,
    dosageForm: 'Tablet',
    dosageStrength: '625mg',
  },
  {
    id: 'drug3',
    tradeName: 'Ciprobay',
    genericName: 'Ciprofloxacin',
    pharmacyId: 'pharmacy1',
    price: 2500,
    dosageForm: 'Tablet',
    dosageStrength: '500mg',
  },
  {
    id: 'drug4',
    tradeName: 'Ventolin',
    genericName: 'Salbutamol',
    pharmacyId: 'pharmacy3',
    price: 1200,
    dosageForm: 'Inhaler',
    dosageStrength: '100mcg/dose',
  },
  {
    id: 'drug5',
    tradeName: 'Flagyl',
    genericName: 'Metronidazole',
    pharmacyId: 'pharmacy2',
    price: 800,
    dosageForm: 'Tablet',
    dosageStrength: '400mg',
  },
  {
    id: 'drug6',
    tradeName: 'Zithromax',
    genericName: 'Azithromycin',
    pharmacyId: 'pharmacy1',
    price: 2700,
    dosageForm: 'Tablet',
    dosageStrength: '500mg',
  },
  {
    id: 'drug7',
    tradeName: 'Dafalgan',
    genericName: 'Paracetamol',
    pharmacyId: 'pharmacy4',
    price: 550,
    dosageForm: 'Suppository',
    dosageStrength: '150mg',
  },
  {
    id: 'drug8',
    tradeName: 'Lopran',
    genericName: 'Loperamide',
    pharmacyId: 'pharmacy3',
    price: 700,
    dosageForm: 'Capsule',
    dosageStrength: '2mg',
  },
  {
    id: 'drug9',
    tradeName: 'Amoxil',
    genericName: 'Amoxicillin',
    pharmacyId: 'pharmacy4',
    price: 1100,
    dosageForm: 'Syrup',
    dosageStrength: '250mg/5ml',
  },
  {
    id: 'drug10',
    tradeName: 'Motilium',
    genericName: 'Domperidone',
    pharmacyId: 'pharmacy1',
    price: 1500,
    dosageForm: 'Tablet',
    dosageStrength: '10mg',
  },
]