export const rootLayoutKeywords = [
  "pharmacy locator",
  "nearest pharmacy",
  "find medication online",
  "online pharmacy search",
  "buy medicine near me",
  "pharmacy management software",
  "global pharmacy directory",
  "pharmacy scheduling tool",
  "on-call pharmacy service",
  "Medyro",
  "pharmacy near me now",
  "24-hour pharmacy near me",
  "emergency pharmacy finder",
  "chemist shop locator",
  "drug store near me",
  "local pharmacy search",
  "online drug store directory",
  "hospital pharmacy locator",
  "pharmacy business management",
  "pharmaceutical inventory system",
  "pharmacy opening hours",
  "on-call pharmacist contact",
  "pharmacy delivery service",
  "pharmacy map app",
  "medicine availability checker",
  "find prescription drugs near me",
  "global chemist directory",
  "medicine price comparison",
  "pharmacy booking system",
  "pharmacy stock management",
  "drug store opening times",
  "health and medicine directory",
  "international pharmacy search",
  "local medicine availability",
  "buy over-the-counter drugs near me",
  "medication store finder",
  "chemist on duty",
  "night pharmacy service",
  "pharmacy API platform",
  "find medications by location",
  "pharmacy and drug shop directory",
  "pharmacy for travelers",
  "pharmacy in my city",
  "nearest drug store app",
  "find pharmacies worldwide",
  "medicine shop open now",
  "online chemist search tool",
  "24/7 drug store locator",
  "pharmacy dashboard software"
]
export const pharmacyKeywords = [
  // General
  "pharmacy Cameroon",
  "pharmacies in Cameroon",
  "pharmacy near me Cameroon",
  "nearest pharmacy Cameroon",
  "find pharmacy Cameroon",
  "Cameroon medications",
  "buy medicine in Cameroon",
  "24-hour pharmacy Cameroon",
  "open pharmacy Cameroon",
  "pharmacy search Cameroon",
  "best pharmacy Cameroon",
  "cheap pharmacy Cameroon",
  "pharmacy services Cameroon",
  "pharmacy Cameroon online",
  "pharmacy phone numbers Cameroon",
  "pharmacy locations Cameroon",
  "Cameroon drug stores",
  "pharmacy opening hours Cameroon",
  "emergency pharmacy Cameroon",
  "late night pharmacy Cameroon",

  // Littoral Region
  "pharmacy Littoral Cameroon",
  "pharmacies in Douala",
  "pharmacy Douala Cameroon",
  "24-hour pharmacy Douala",
  "pharmacies in Nkongsamba",
  "pharmacy Nkongsamba",
  "pharmacies in Manjo",
  "pharmacy Manjo Cameroon",
  "best pharmacy Douala",
  "nearest pharmacy Douala",

  // Centre Region
  "pharmacy Centre Cameroon",
  "pharmacies in Yaoundé",
  "pharmacy Yaoundé Cameroon",
  "24-hour pharmacy Yaoundé",
  "pharmacies in Mfou",
  "pharmacy Mfou Cameroon",
  "pharmacies in Obala",
  "pharmacy Obala Cameroon",
  "best pharmacy Yaoundé",
  "nearest pharmacy Yaoundé",

  // Southwest Region
  "pharmacy Southwest Cameroon",
  "pharmacies in Buea",
  "pharmacy Buea Cameroon",
  "24-hour pharmacy Buea",
  "pharmacies in Limbe",
  "pharmacy Limbe Cameroon",
  "pharmacies in Tiko",
  "pharmacy Tiko Cameroon",
  "best pharmacy Buea",
  "nearest pharmacy Buea",

  // Northwest Region
  "pharmacy Northwest Cameroon",
  "pharmacies in Bamenda",
  "pharmacy Bamenda Cameroon",
  "24-hour pharmacy Bamenda",
  "pharmacies in Kumbo",
  "pharmacy Kumbo Cameroon",
  "pharmacies in Wum",
  "pharmacy Wum Cameroon",
  "best pharmacy Bamenda",
  "nearest pharmacy Bamenda",

  // West Region
  "pharmacy West Cameroon",
  "pharmacies in Bafoussam",
  "pharmacy Bafoussam Cameroon",
  "24-hour pharmacy Bafoussam",
  "pharmacies in Dschang",
  "pharmacy Dschang Cameroon",
  "pharmacies in Foumban",
  "pharmacy Foumban Cameroon",
  "best pharmacy Bafoussam",
  "nearest pharmacy Bafoussam",

  // North Region
  "pharmacy North Cameroon",
  "pharmacies in Garoua",
  "pharmacy Garoua Cameroon",
  "24-hour pharmacy Garoua",
  "pharmacies in Guider",
  "pharmacy Guider Cameroon",
  "pharmacies in Poli",
  "pharmacy Poli Cameroon",
  "best pharmacy Garoua",
  "nearest pharmacy Garoua",

  // Far North Region
  "pharmacy Far North Cameroon",
  "pharmacies in Maroua",
  "pharmacy Maroua Cameroon",
  "24-hour pharmacy Maroua",
  "pharmacies in Mokolo",
  "pharmacy Mokolo Cameroon",
  "pharmacies in Kousséri",
  "pharmacy Kousséri Cameroon",
  "best pharmacy Maroua",
  "nearest pharmacy Maroua",

  // Adamawa Region
  "pharmacy Adamawa Cameroon",
  "pharmacies in Ngaoundéré",
  "pharmacy Ngaoundéré Cameroon",
  "24-hour pharmacy Ngaoundéré",
  "pharmacies in Meiganga",
  "pharmacy Meiganga Cameroon",
  "pharmacies in Tibati",
  "pharmacy Tibati Cameroon",
  "best pharmacy Ngaoundéré",
  "nearest pharmacy Ngaoundéré",

  // East Region
  "pharmacy East Cameroon",
  "pharmacies in Bertoua",
  "pharmacy Bertoua Cameroon",
  "24-hour pharmacy Bertoua",
  "pharmacies in Batouri",
  "pharmacy Batouri Cameroon",
  "pharmacies in Abong-Mbang",
  "pharmacy Abong-Mbang Cameroon",
  "best pharmacy Bertoua",
  "nearest pharmacy Bertoua",

  // South Region
  "pharmacy South Cameroon",
  "pharmacies in Ebolowa",
  "pharmacy Ebolowa Cameroon",
  "24-hour pharmacy Ebolowa",
  "pharmacies in Kribi",
  "pharmacy Kribi Cameroon",
  "pharmacies in Sangmélima",
  "pharmacy Sangmélima Cameroon",
  "best pharmacy Ebolowa",
  "nearest pharmacy Ebolowa"
];
