export const rootLayoutKeywords = [
  "pharmacy locator",
  "nearest pharmacy",
  "find medication online",
  "online pharmacy search",
  "buy medicine near me",
  "pharmacy management software",
  "global pharmacy directory",
  "pharmacy scheduling tool",
  "on-call pharmacy service",
  "Medyro",
  "pharmacy near me now",
  "24-hour pharmacy near me",
  "emergency pharmacy finder",
  "chemist shop locator",
  "drug store near me",
  "local pharmacy search",
  "online drug store directory",
  "hospital pharmacy locator",
  "pharmacy business management",
  "pharmaceutical inventory system",
  "pharmacy opening hours",
  "on-call pharmacist contact",
  "pharmacy delivery service",
  "pharmacy map app",
  "medicine availability checker",
  "find prescription drugs near me",
  "global chemist directory",
  "medicine price comparison",
  "pharmacy booking system",
  "pharmacy stock management",
  "drug store opening times",
  "health and medicine directory",
  "international pharmacy search",
  "local medicine availability",
  "buy over-the-counter drugs near me",
  "medication store finder",
  "chemist on duty",
  "night pharmacy service",
  "pharmacy API platform",
  "find medications by location",
  "pharmacy and drug shop directory",
  "pharmacy for travelers",
  "pharmacy in my city",
  "nearest drug store app",
  "find pharmacies worldwide",
  "medicine shop open now",
  "online chemist search tool",
  "24/7 drug store locator",
  "pharmacy dashboard software"
]