export const englishRootLayoutKeywords = [
  "pharmacy locator",
  "nearest pharmacy",
  "find medication online",
  "online pharmacy search",
  "buy medicine near me",
  "pharmacy management software",
  "global pharmacy directory",
  "pharmacy scheduling tool",
  "on-call pharmacy service",
  "Medyro",
  "pharmacy near me now",
  "24-hour pharmacy near me",
  "emergency pharmacy finder",
  "chemist shop locator",
  "drug store near me",
  "local pharmacy search",
  "online drug store directory",
  "hospital pharmacy locator",
  "pharmacy business management",
  "pharmaceutical inventory system",
  "pharmacy opening hours",
  "on-call pharmacist contact",
  "pharmacy delivery service",
  "pharmacy map app",
  "medicine availability checker",
  "find prescription drugs near me",
  "global chemist directory",
  "medicine price comparison",
  "pharmacy booking system",
  "pharmacy stock management",
  "drug store opening times",
  "health and medicine directory",
  "international pharmacy search",
  "local medicine availability",
  "buy over-the-counter drugs near me",
  "medication store finder",
  "chemist on duty",
  "night pharmacy service",
  "pharmacy API platform",
  "find medications by location",
  "pharmacy and drug shop directory",
  "pharmacy for travelers",
  "pharmacy in my city",
  "nearest drug store app",
  "find pharmacies worldwide",
  "medicine shop open now",
  "online chemist search tool",
  "24/7 drug store locator",
  "pharmacy dashboard software"
]
export const frenchRootLayoutKeywords = [
  "localisateur de pharmacie",
  "pharmacie la plus proche",
  "trouver des médicaments en ligne",
  "recherche de pharmacie en ligne",
  "acheter des médicaments près de chez moi",
  "logiciel de gestion de pharmacie",
  "annuaire mondial des pharmacies",
  "outil de planification des pharmacies",
  "service de pharmacie de garde",
  "Medyro",
  "pharmacie près de moi maintenant",
  "pharmacie ouverte 24h/24 près de chez moi",
  "localisateur de pharmacie d'urgence",
  "localisateur de pharmacie / parapharmacie",
  "magasin de médicaments près de chez moi",
  "recherche de pharmacie locale",
  "annuaire des pharmacies en ligne",
  "localisateur de pharmacie hospitalière",
  "gestion d'entreprise pharmaceutique",
  "système de gestion d'inventaire pharmaceutique",
  "horaires d'ouverture de pharmacie",
  "contact pharmacien de garde",
  "service de livraison de pharmacie",
  "application carte des pharmacies",
  "vérificateur de disponibilité de médicaments",
  "trouver des médicaments sur ordonnance près de chez moi",
  "annuaire mondial des pharmacies / parapharmacies",
  "comparaison des prix des médicaments",
  "système de réservation en pharmacie",
  "gestion des stocks de pharmacie",
  "horaires d'ouverture de la pharmacie",
  "annuaire santé et médicaments",
  "recherche internationale de pharmacie",
  "disponibilité locale des médicaments",
  "acheter des médicaments en vente libre près de chez moi",
  "localisateur de magasin de médicaments",
  "pharmacien de garde",
  "service de pharmacie de nuit",
  "plateforme API pharmacie",
  "trouver des médicaments par localisation",
  "annuaire des pharmacies et parapharmacies",
  "pharmacie pour voyageurs",
  "pharmacie dans ma ville",
  "application magasin de médicaments le plus proche",
  "trouver des pharmacies dans le monde entier",
  "magasin de médicaments ouvert maintenant",
  "outil de recherche de pharmacie en ligne",
  "localisateur de pharmacie ouverte 24/7",
  "logiciel tableau de bord pharmacie"
]


export const rootLayoutKeywords = [
 ...englishRootLayoutKeywords, ...frenchRootLayoutKeywords
 
]
export const englishPharmacyKeywords = [
  // General
  "pharmacy Cameroon",
  "pharmacies in Cameroon",
  "pharmacy near me Cameroon",
  "nearest pharmacy Cameroon",
  "find pharmacy Cameroon",
  "Cameroon medications",
  "buy medicine in Cameroon",
  "24-hour pharmacy Cameroon",
  "open pharmacy Cameroon",
  "pharmacy search Cameroon",
  "best pharmacy Cameroon",
  "cheap pharmacy Cameroon",
  "pharmacy services Cameroon",
  "pharmacy Cameroon online",
  "pharmacy phone numbers Cameroon",
  "pharmacy locations Cameroon",
  "Cameroon drug stores",
  "pharmacy opening hours Cameroon",
  "emergency pharmacy Cameroon",
  "late night pharmacy Cameroon",

  // Littoral Region
  "pharmacy Littoral Cameroon",
  "pharmacies in Douala",
  "pharmacy Douala Cameroon",
  "24-hour pharmacy Douala",
  "pharmacies in Nkongsamba",
  "pharmacy Nkongsamba",
  "pharmacies in Manjo",
  "pharmacy Manjo Cameroon",
  "best pharmacy Douala",
  "nearest pharmacy Douala",

  // Centre Region
  "pharmacy Centre Cameroon",
  "pharmacies in Yaoundé",
  "pharmacy Yaoundé Cameroon",
  "24-hour pharmacy Yaoundé",
  "pharmacies in Mfou",
  "pharmacy Mfou Cameroon",
  "pharmacies in Obala",
  "pharmacy Obala Cameroon",
  "best pharmacy Yaoundé",
  "nearest pharmacy Yaoundé",

  // Southwest Region
  "pharmacy Southwest Cameroon",
  "pharmacies in Buea",
  "pharmacy Buea Cameroon",
  "24-hour pharmacy Buea",
  "pharmacies in Limbe",
  "pharmacy Limbe Cameroon",
  "pharmacies in Tiko",
  "pharmacy Tiko Cameroon",
  "best pharmacy Buea",
  "nearest pharmacy Buea",

  // Northwest Region
  "pharmacy Northwest Cameroon",
  "pharmacies in Bamenda",
  "pharmacy Bamenda Cameroon",
  "24-hour pharmacy Bamenda",
  "pharmacies in Kumbo",
  "pharmacy Kumbo Cameroon",
  "pharmacies in Wum",
  "pharmacy Wum Cameroon",
  "best pharmacy Bamenda",
  "nearest pharmacy Bamenda",

  // West Region
  "pharmacy West Cameroon",
  "pharmacies in Bafoussam",
  "pharmacy Bafoussam Cameroon",
  "24-hour pharmacy Bafoussam",
  "pharmacies in Dschang",
  "pharmacy Dschang Cameroon",
  "pharmacies in Foumban",
  "pharmacy Foumban Cameroon",
  "best pharmacy Bafoussam",
  "nearest pharmacy Bafoussam",

  // North Region
  "pharmacy North Cameroon",
  "pharmacies in Garoua",
  "pharmacy Garoua Cameroon",
  "24-hour pharmacy Garoua",
  "pharmacies in Guider",
  "pharmacy Guider Cameroon",
  "pharmacies in Poli",
  "pharmacy Poli Cameroon",
  "best pharmacy Garoua",
  "nearest pharmacy Garoua",

  // Far North Region
  "pharmacy Far North Cameroon",
  "pharmacies in Maroua",
  "pharmacy Maroua Cameroon",
  "24-hour pharmacy Maroua",
  "pharmacies in Mokolo",
  "pharmacy Mokolo Cameroon",
  "pharmacies in Kousséri",
  "pharmacy Kousséri Cameroon",
  "best pharmacy Maroua",
  "nearest pharmacy Maroua",

  // Adamawa Region
  "pharmacy Adamawa Cameroon",
  "pharmacies in Ngaoundéré",
  "pharmacy Ngaoundéré Cameroon",
  "24-hour pharmacy Ngaoundéré",
  "pharmacies in Meiganga",
  "pharmacy Meiganga Cameroon",
  "pharmacies in Tibati",
  "pharmacy Tibati Cameroon",
  "best pharmacy Ngaoundéré",
  "nearest pharmacy Ngaoundéré",

  // East Region
  "pharmacy East Cameroon",
  "pharmacies in Bertoua",
  "pharmacy Bertoua Cameroon",
  "24-hour pharmacy Bertoua",
  "pharmacies in Batouri",
  "pharmacy Batouri Cameroon",
  "pharmacies in Abong-Mbang",
  "pharmacy Abong-Mbang Cameroon",
  "best pharmacy Bertoua",
  "nearest pharmacy Bertoua",

  // South Region
  "pharmacy South Cameroon",
  "pharmacies in Ebolowa",
  "pharmacy Ebolowa Cameroon",
  "24-hour pharmacy Ebolowa",
  "pharmacies in Kribi",
  "pharmacy Kribi Cameroon",
  "pharmacies in Sangmélima",
  "pharmacy Sangmélima Cameroon",
  "best pharmacy Ebolowa",
  "nearest pharmacy Ebolowa"
];
export const frenchPharmacyKeywords = [
  // Général
  "pharmacie Cameroun",
  "pharmacies au Cameroun",
  "pharmacie près de moi Cameroun",
  "pharmacie la plus proche Cameroun",
  "trouver une pharmacie Cameroun",
  "médicaments Cameroun",
  "acheter des médicaments au Cameroun",
  "pharmacie ouverte 24h/24 Cameroun",
  "pharmacie ouverte Cameroun",
  "recherche de pharmacie Cameroun",
  "meilleure pharmacie Cameroun",
  "pharmacie pas chère Cameroun",
  "services de pharmacie Cameroun",
  "pharmacie en ligne Cameroun",
  "numéros de téléphone pharmacie Cameroun",
  "emplacements des pharmacies Cameroun",
  "magasins de médicaments Cameroun",
  "horaires d'ouverture pharmacie Cameroun",
  "pharmacie d'urgence Cameroun",
  "pharmacie de nuit Cameroun",

  // Région du Littoral
  "pharmacie Littoral Cameroun",
  "pharmacies à Douala",
  "pharmacie Douala Cameroun",
  "pharmacie ouverte 24h/24 Douala",
  "pharmacies à Nkongsamba",
  "pharmacie Nkongsamba",
  "pharmacies à Manjo",
  "pharmacie Manjo Cameroun",
  "meilleure pharmacie Douala",
  "pharmacie la plus proche Douala",

  // Région du Centre
  "pharmacie Centre Cameroun",
  "pharmacies à Yaoundé",
  "pharmacie Yaoundé Cameroun",
  "pharmacie ouverte 24h/24 Yaoundé",
  "pharmacies à Mfou",
  "pharmacie Mfou Cameroun",
  "pharmacies à Obala",
  "pharmacie Obala Cameroun",
  "meilleure pharmacie Yaoundé",
  "pharmacie la plus proche Yaoundé",

  // Région du Sud-Ouest
  "pharmacie Sud-Ouest Cameroun",
  "pharmacies à Buéa",
  "pharmacie Buéa Cameroun",
  "pharmacie ouverte 24h/24 Buéa",
  "pharmacies à Limbé",
  "pharmacie Limbé Cameroun",
  "pharmacies à Tiko",
  "pharmacie Tiko Cameroun",
  "meilleure pharmacie Buéa",
  "pharmacie la plus proche Buéa",

  // Région du Nord-Ouest
  "pharmacie Nord-Ouest Cameroun",
  "pharmacies à Bamenda",
  "pharmacie Bamenda Cameroun",
  "pharmacie ouverte 24h/24 Bamenda",
  "pharmacies à Kumbo",
  "pharmacie Kumbo Cameroun",
  "pharmacies à Wum",
  "pharmacie Wum Cameroun",
  "meilleure pharmacie Bamenda",
  "pharmacie la plus proche Bamenda",

  // Région de l’Ouest
  "pharmacie Ouest Cameroun",
  "pharmacies à Bafoussam",
  "pharmacie Bafoussam Cameroun",
  "pharmacie ouverte 24h/24 Bafoussam",
  "pharmacies à Dschang",
  "pharmacie Dschang Cameroun",
  "pharmacies à Foumban",
  "pharmacie Foumban Cameroun",
  "meilleure pharmacie Bafoussam",
  "pharmacie la plus proche Bafoussam",

  // Région du Nord
  "pharmacie Nord Cameroun",
  "pharmacies à Garoua",
  "pharmacie Garoua Cameroun",
  "pharmacie ouverte 24h/24 Garoua",
  "pharmacies à Guider",
  "pharmacie Guider Cameroun",
  "pharmacies à Poli",
  "pharmacie Poli Cameroun",
  "meilleure pharmacie Garoua",
  "pharmacie la plus proche Garoua",

  // Région de l’Extrême-Nord
  "pharmacie Extrême-Nord Cameroun",
  "pharmacies à Maroua",
  "pharmacie Maroua Cameroun",
  "pharmacie ouverte 24h/24 Maroua",
  "pharmacies à Mokolo",
  "pharmacie Mokolo Cameroun",
  "pharmacies à Kousséri",
  "pharmacie Kousséri Cameroun",
  "meilleure pharmacie Maroua",
  "pharmacie la plus proche Maroua",

  // Région de l’Adamaoua
  "pharmacie Adamaoua Cameroun",
  "pharmacies à Ngaoundéré",
  "pharmacie Ngaoundéré Cameroun",
  "pharmacie ouverte 24h/24 Ngaoundéré",
  "pharmacies à Meiganga",
  "pharmacie Meiganga Cameroun",
  "pharmacies à Tibati",
  "pharmacie Tibati Cameroun",
  "meilleure pharmacie Ngaoundéré",
  "pharmacie la plus proche Ngaoundéré",

  // Région de l’Est
  "pharmacie Est Cameroun",
  "pharmacies à Bertoua",
  "pharmacie Bertoua Cameroun",
  "pharmacie ouverte 24h/24 Bertoua",
  "pharmacies à Batouri",
  "pharmacie Batouri Cameroun",
  "pharmacies à Abong-Mbang",
  "pharmacie Abong-Mbang Cameroun",
  "meilleure pharmacie Bertoua",
  "pharmacie la plus proche Bertoua",

  // Région du Sud
  "pharmacie Sud Cameroun",
  "pharmacies à Ebolowa",
  "pharmacie Ebolowa Cameroun",
  "pharmacie ouverte 24h/24 Ebolowa",
  "pharmacies à Kribi",
  "pharmacie Kribi Cameroun",
  "pharmacies à Sangmélima",
  "pharmacie Sangmélima Cameroun",
  "meilleure pharmacie Ebolowa",
  "pharmacie la plus proche Ebolowa"
];


export const pharmacyKeywords = [
...englishPharmacyKeywords, frenchPharmacyKeywords
];