"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppProvider from "@/context/AppProvider";
import { Footer } from "@/components/index";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/libs/queryClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Campharm",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: "url('/bg_image.jpg')",
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          backgroundPosition: "center",
          minHeight: "100vh",
        }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ToastContainer />
        <QueryClientProvider client={queryClient}>
          <AppProvider>
            {/* <Header /> */}
            <main className="min-h-[85dvh] mx-auto ">{children}</main>
            <Footer />
          </AppProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
