import apple_logo from './photos/apple_logo.png'
import banginic_logo from './photos/banginic_logo.png'
import close_menu from './photos/close_menu.png'
import doctor from './photos/doctor.png'
import email from './photos/email.png'
import france_flag from './photos/france_flag.png'
import google_logo from './photos/google_logo.png'
import location from './photos/location.png'
import password from './photos/password.png'
import person from './photos/person.png'
import phone from './photos/phone.png'
import pill from './photos/pill.png'
import uk_flag from './photos/uk_flag.png'
import start from './photos/start.png'
import at from './photos/@.png'
import instagram from './photos/instagram.png'
import twitter from './photos/twitter.png'
import facebook from './photos/facebook.png'
import place_holder_img from './photos/@.png'
import menu_open from './photos/menu_icon.png'
import search_icon from './photos/search_icon.png'
import back from './photos/back.png'
import direction from './photos/direction.png'
import verified from './photos/verified.png'
import no_message from './photos/no_message.png'
import offline from './photos/offline.png'
import pharmacy from './photos/pharmacy.png'
import about from './photos/about.png'
import update from './photos/update.png'
import blog from './photos/blog.png'
import town_logo from './photos/town.png'
import region from './photos/region.png'
import bg_image from './photos/bg_image.jpeg'
import no_drug from './photos/no_drug.png'
import pharmacy_icon  from './photos/pharmacy_icon.png'

export { pharmacy, about, update, blog , town_logo, region, bg_image, no_drug, pharmacy_icon,
    apple_logo, banginic_logo, close_menu, doctor, menu_open, place_holder_img, email, france_flag, google_logo, location, password, person, phone, pill, uk_flag,
    facebook, instagram, twitter, start, at, search_icon, back, direction, verified, no_message, offline
}